### ISSUE TITLE
I will get "sjwt"  in my project!

### ISSUE THREAD

**Issue by chaseSpace** [brianvoe/sjwt#1]
1. Hope more alg in sjwt. HS256 alone is not enough !
2. You can add sjwt to [jwt.io](https://jwt.io/#debugger), get more "fans" for sjwt.

**Comment by brianvoe** [comment]
2. I was able to get sjwt added to jwt.io its the last on the go list.
1. This is something im open to but 256 is the majority of what people use and if i introduced anything else it would not keep it as simple as i would like.
